# streamlit_app.py
import os
import pdfminer.high_level
import docx
import streamlit as st
from google import genai

# Configure Gemini API — key comes from Streamlit Cloud Secrets
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# Function to extract text from PDF/DOCX
def extract_text(file_path):
    if file_path.endswith(".pdf"):
        return pdfminer.high_level.extract_text(file_path)
    elif file_path.endswith(".docx"):
        doc = docx.Document(file_path)
        return "\n".join([p.text for p in doc.paragraphs])
    else:
        return ""

# Function to detect AI percentage
def get_ai_percentage(text):
    prompt = f"""
    Analyze the following text and estimate the probability it was generated by AI.
    Respond ONLY with a number from 0 to 100 and a short explanation.

    Text:
    {text}
    """
    response = genai.chat.create(
        model="gemini-1.5-flash",
        messages=[
            {"role": "system", "content": "You are an AI detection assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.last.message.content

# Function to convert text to human-like style
def convert_to_human(text):
    prompt = f"""
    Rewrite the following text so it looks like a real student wrote it:
    - Natural, casual language
    - Minor mistakes allowed
    - Zero AI tone
    - Keep the original meaning

    Text:
    {text}
    """
    response = genai.chat.create(
        model="gemini-1.5-flash",
        messages=[
            {"role": "system", "content": "You are a student-style rewriting assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.last.message.content

# Streamlit UI
st.title("AI Detector & Humanizer")

uploaded_file = st.file_uploader("Upload PDF or DOCX", type=["pdf", "docx"])
if uploaded_file:
    with open("temp_file", "wb") as f:
        f.write(uploaded_file.getbuffer())
    
    # Extract text
    text = extract_text("temp_file")
    
    # Detect AI %
    ai_result = get_ai_percentage(text)
    st.subheader("AI Detection Result")
    st.write(ai_result)
    
    # Convert to human-like text
    human_text = convert_to_human(text)
    st.subheader("Human-like Version")
    st.text_area("Output Text", human_text, height=400)
