import { GoogleGenAI, Type } from "@google/genai";
import { DetectionResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const detectAIContent = async (text: string): Promise<DetectionResult> => {
  try {
    const prompt = `
    Analyze the following text and estimate the probability it was generated by AI.
    Provide a percentage (0 to 100) where 100 is definitely AI and 0 is definitely human.
    Provide a short, concise explanation (max 2 sentences) for your reasoning.

    Text to analyze:
    ${text.slice(0, 10000)} 
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            percentage: { type: Type.INTEGER },
            explanation: { type: Type.STRING },
          },
          required: ["percentage", "explanation"],
        }
      }
    });

    const result = JSON.parse(response.text || "{}");
    
    return {
      percentage: result.percentage ?? 0,
      explanation: result.explanation ?? "Could not analyze text.",
    };
  } catch (error) {
    console.error("Error in AI detection:", error);
    throw new Error("Failed to analyze text. Please try again.");
  }
};

export const humanizeContent = async (text: string): Promise<string> => {
  try {
    const prompt = `
    Rewrite the following text to sound more natural, human, and authentic. 
    It should sound like it was written by a real person (e.g., a student or professional, depending on context).
    
    Guidelines:
    - Use natural sentence variation.
    - Avoid robotic transitions.
    - It is okay to have very minor stylistic imperfections that make it feel human.
    - Keep the original meaning and core information intact.
    - Do NOT make it sound overly slang-heavy unless the original text implies it.
    
    Text to rewrite:
    ${text.slice(0, 10000)}
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text || "Could not generate humanized text.";
  } catch (error) {
    console.error("Error in text humanization:", error);
    throw new Error("Failed to humanize text. Please try again.");
  }
};